# Generated by Django 3.2.15 on 2022-09-24 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperbookorder',
            name='dispatched_at',
        ),
        migrations.RemoveField(
            model_name='paperbookorder',
            name='is_dispatched',
        ),
        migrations.RemoveField(
            model_name='paperbookorder',
            name='is_preparing',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paperbookorder',
            name='user_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.useraddress'),
        ),
        migrations.AlterField(
            model_name='paperbookordertrack',
            name='tracker',
            field=models.CharField(choices=[('cancelled', 'CANCELLED'), ('preparing', 'PREPARING'), ('dispatched', 'DISPATCHED'), ('moving', 'MOVING'), ('delivered', 'DELIVERED'), ('outofdelivery', 'OUT_OF_DELIVERY')], max_length=20),
        ),
    ]
