# Generated by Django 3.2.15 on 2022-09-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220924_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperbookorder',
            name='handover_to_transporter_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='paperbookorder',
            name='is_handover_to_transporter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paperbookordertrack',
            name='tracker',
            field=models.CharField(choices=[('cancelled', 'CANCELLED'), ('preparing', 'PREPARING'), ('dispatched', 'DISPATCHED'), ('handover', 'HANDOVER_TO_TRANSPORT'), ('moving', 'MOVING'), ('delivered', 'DELIVERED'), ('outofdelivery', 'OUT_OF_DELIVERY')], max_length=20),
        ),
    ]
