# Generated by Django 3.2.15 on 2022-09-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20220924_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperbookorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='paperbookorder',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
